### ISSUE TITLE
Allow Facebook.init without appId

### ISSUE THREAD

**Issue by ThatGuySam** [erikhagreis/fb-sdk-wrapper#7]
Facebook allows initializing the SDK without an app ID when using it for simple post embeds. 

Here's an example: 

```
<script>
  window.fbAsyncInit = function() {
    FB.init({
      xfbml      : true,
      version    : 'v7.0'
    });
  }; 
</script>
<script async defer src="https://connect.facebook.net/en_US/sdk.js"></script>
  
<div 
  class="fb-post" 
  data-href="https://www.facebook.com/20531316728/posts/10154009990506729/" 
  data-width="500"></div>
```

This allows for simple usage without having to register a Facebook app and go through App Review. 

[Source](https://developers.facebook.com/docs/plugins/embedded-posts/#wordpress) 

[Working Example](https://jsfiddle.net/thatguysam/sr2eu1dj/)

**Comment by erikhagreis** [comment]
Ahh app review... gotta love it. I've reviewed the docs and looks indeed that `appId` is not strictly required. I'll remove the check.

**Comment by ThatGuySam** [comment]
Gracias!!
